
---
- hosts: web
  become: true

  tasks:
    - name: Update packages
      shell: dnf update -y

    - name: Install Docker
      shell: dnf install docker -y

    - name: Start Docker
      shell: |
          systemctl enable docker
          systemctl start docker