name: Docker Ci CD piplelne
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout source code
        uses: actions/checkout@v4
     
      - name: docker build
        run: docker build -t resume-analyser .
